Repository nurion4hep/HEP-CNN, pull requests merged in 2020-08, with the labels that each got.

#87 Update torch_model_largekernel.py
  python/HEPCNN/torch_model_largekernel.py
Labels: bug

#88 Select Large kernel models
  run/train_labelByUser.py
Labels: enhancement

#89 fix wrong sign to keep the best weight
  run/train_labelByUser.py
Labels: bug

#91 bug fix in large kernel module
  python/HEPCNN/torch_model_largekernel.py
Labels: bug

#86 Cleanup
  python/HEPCNN/keras_dataGenerator.py
  python/HEPCNN/keras_model_default.py
  python/HEPCNN/model_circpad.py
  python/HEPCNN/model_default.py
  python/HEPCNN/model_largekernel.py
  python/HEPCNN/model_original.py
  python/HEPCNN/torch_dataset.py
  python/HEPCNN/torch_dataset_splited.py
  run/run_keras_nurion.sh
  run/train_keras.py
  run/train_labelByUser.py
  run/train_torch.py
  torch_model_largekernel.py
Labels: bug, cleanup
